apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-blue
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: nodeapp-bg
  template:
    metadata:
      labels:
        app: nodeapp-bg
        color: blue
    spec:
      containers:
        - name: front-end
          image: durgaoct1989/nodejs-app-demo
          ports:
            - containerPort: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
